name: exploreindore
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  
  shared_preferences: "^0.4.2"
  curved_navigation_bar: ^0.1.26
  flutter_launcher_icons: "^0.7.0"
  cloud_firestore: ^0.8.2
  url_launcher: any 
  carousel_pro: ^0.0.13
  firebase_auth: any
  google_sign_in: ^3.2.2
  flare_flutter: any
  


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "Image/map.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - Image/1.jpg
  - Image/2.jpg
  - Image/3.jpg
  - Image/logo.gif
  - Image/2m.png
  - Image/IndoreMontage.png
  - Image/Rajwada.png
  - Image/Sarafa.png
  - Image/sheesh-mahal.png
  - Image/Raj1.jpg
  - Image/Raj2.jpg
  - Image/Raj3.jpg
  - Image/Sar1.jpg
  - Image/Sar2.jpg
  - Image/Sar3.jpg
  - Image/CB1.jpg
  - Image/CB2.jpg
  - Image/CB3.jpg
  - Image/Chappan1.jpg
  - Image/Chappan2.jpg
  - Image/Chappan3.jpg  
  - Image/BK1.jpg
  - Image/BK2.jpg
  - Image/BK3.jpg  
  - Image/LalBagh1.jpg
  - Image/LalBagh2.jpg
  - Image/LalBagh3.jpg   
  - Image/JamGate1.jpg
  - Image/JamGate2.jpg
  - Image/JamGate3.jpg
  - Image/IMus1.jpg
  - Image/IMus2.jpg
  - Image/IMus3.jpg 
  - Image/Crescent1.jpg
  - Image/Crescent2.jpg
  - Image/Crescent3.jpg
  - Image/MayankBlue1.png
  - Image/MayankBlue2.png
  - Image/MayankBlue3.png
  - Image/Zoo1.jpg
  - Image/Zoo2.jpg
  - Image/Zoo3.jpg 
  - Image/Nick.jpg 
  - Image/Momo.jpg 
  - Image/Patil.jpg 
  - Image/Loader.flr
  
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


  
